### PR TITLE
Added how to notebook for demo purpose

### PR DESCRIPTION
**Pull request by mhmohona**
Here I am proposing template for how to section. 
I will continue working on this in future after getting suggestion about it. 

I have used two different style for How to create a One Dimensional NumPy Array and How to create a Boolean array section. Which one do you think should be followed?

### CODE REVIEW

**Comment by rossbar** [comment]
@mhmohona sorry - I hadn't set up any continuous integration services as I wasn't expecting PR's. I took care of that now: I'm going to try to close/reopen to see if I can trigger the PR (I hope you don't mind me using your PR to test it!)

**Comment by rossbar** [comment]
First of all, thanks for taking the time to put together this how-to @mhmohona !

I went ahead and created a new branch starting from bfc7348 - I wanted to test the CI, which required me to rebase your work on master. I did this in a new branch and opened a new PR (#8) only because I didn't want to force-push to your branch and cause merge conflicts without telling you. The upshot is you can now see the html-rendered version of the "how to" you submitted [here](https://10-269499043-gh.circle-artifacts.com/0/_build/html/index.html).

As I mentioned, I wasn't expecting PRs with new templates/content to this repository. The main goal here is to demonstrate/experiment with various tooling/configuration options rather than focusing on new tutorial content. The [numpy-tutorials repository](https://github.com/numpy/numpy-tutorials/) will (likely) be the official repository for new content, though that's still in early stages of development. It will take time for the project to more fully take shape, so I recommend you keep an eye on that repo for updates. 

Regarding the "how-to" article you submitted - thank you for putting it together; the content is quite nice. You might also be interested in checking out the [Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html) and especially the [Absolute beginner's tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) which have content targeted to a similar audience. IMO the article you've submitted seems more along the lines of an *example* rather than what I would call a "template" given all the concrete material in it. If you are interested in contributing to the templates for the new documentation materials, I would recommend taking a look at:
 - [NEP 44](https://numpy.org/neps/nep-0044-restructuring-numpy-docs.html), which presents the high-level goals/outline for the re-organization of NumPy's documentation.
 - [These documentation guidelines](https://documentation.divio.com/introduction/) for a nice overview/description of the various documentation categories discussed in the NEP (thanks @bjnath for the reference).
 - @bjnath 's PR numpy/numpy-tutorials#11 that implements a notebook-based template for the "tutorial" category of documentation, an excellent example of what a template might look like.

I hope some of this information is useful to you! I will leave the PR(s) open (feel free to incorporate the changes from #8 to your own `How-to` branch and I will happily close it), and you are welcome to continue adding material for testing tutorial-writing in Jupyter notebook format, but just know that material contributed here won't be incorporated in the official `numpy-tutorials` - you'd have to submit material to that repo directly for consideration!

**Comment by mhmohona** [comment]
Its completely fine! :D 
Thanks for reminding me about format, I will work on those. 
I am aware of that its not the main repo, I am not supposed to add anything here. Actually here I asked for your review, this is going to be my first major contribution to a big open source community like NumPy, so I am very nervous if things are okay or not. 😅  

THANK YOU so much for managing time for writing such long response. ^_^

**Comment by rossbar** [comment]
>  Actually here I asked for your review, this is going to be my first major contribution to a big open source community like NumPy, so I am very nervous if things are okay or not

That's great, your contributions are more than welcome! I'm happy to help however I can :) Please don't hesitate to ping me about any questions/comments you have... I may not have the answer, but I'll do my best to point you to someone who does!

**Pull request closed without merging**
